{-# LANGUAGE OverloadedStrings #-}

module Main where

import Data.Text (pack, stripEnd)
import Day1 (part1, part2)
import Day10 (part1, part2)
import Day11 (part1, part2)
import Day12 (part1, part2)
import Day13 (part1, part2)
import Day14 (part1, part2)
import Day17 (part1, part2)
import Day2 (part1, part2)
import Day3 (part1, part2)
import Day4 (part1, part2)
import Day5 (part1, part2)
import Day6 (part1, part2)
import Day7 (part1, part2)
import Day8 (part1, part2)
import Day9 (part1, part2)
import System.Environment
import Text.Printf (printf)

main :: IO ()
main = do
  args <- getArgs
  contents <- stripEnd . pack <$> readFile (args !! 2)
  case take 2 args of
    ["day1", "1"] -> printf "%d\n" (Day1.part1 contents)
    ["day1", "2"] -> printf "%d\n" (Day1.part2 contents)
    ["day2", "1"] -> printf "%d\n" (Day2.part1 contents)
    ["day2", "2"] -> printf "%d\n" (Day2.part2 contents)
    ["day3", "1"] -> printf "%d\n" (Day3.part1 contents)
    ["day3", "2"] -> printf "%d\n" (Day3.part2 contents)
    ["day4", "1"] -> printf "%d\n" (Day4.part1 contents)
    ["day4", "2"] -> printf "%d\n" (Day4.part2 contents)
    ["day5", "1"] -> printf "%s\n" (Day5.part1 contents)
    ["day5", "2"] -> printf "%s\n" (Day5.part2 contents)
    ["day6", "1"] -> printf "%d\n" (Day6.part1 contents)
    ["day6", "2"] -> printf "%d\n" (Day6.part2 contents)
    ["day7", "1"] -> printf "%d\n" (Day7.part1 contents)
    ["day7", "2"] -> printf "%d\n" (Day7.part2 contents)
    ["day8", "1"] -> printf "%d\n" (Day8.part1 contents)
    ["day8", "2"] -> printf "%d\n" (Day8.part2 contents)
    ["day9", "1"] -> printf "%d\n" (Day9.part1 contents)
    ["day9", "2"] -> printf "%d\n" (Day9.part2 contents)
    ["day10", "1"] -> printf "%d\n" (Day10.part1 contents)
    ["day10", "2"] -> printf "%s\n" (Day10.part2 contents)
    ["day11", "1"] -> printf "%d\n" (Day11.part1 contents)
    ["day11", "2"] -> printf "%d\n" (Day11.part2 contents)
    ["day12", "1"] -> printf "%d\n" (Day12.part1 contents)
    ["day12", "2"] -> printf "%d\n" (Day12.part2 contents)
    ["day13", "1"] -> printf "%d\n" (Day13.part1 contents)
    ["day13", "2"] -> printf "%d\n" (Day13.part2 contents)
    ["day14", "1"] -> printf "%d\n" (Day14.part1 contents)
    ["day14", "2"] -> printf "%d\n" (Day14.part2 contents)
    ["day17", "1"] -> printf "%d\n" (Day17.part1 contents)
    ["day17", "2"] -> printf "%d\n" (Day17.part2 contents)
    _ -> do
      putStrLn "Not found"
